### ISSUE TITLE
SDL Fails to Link in Debian Stretch with Wayland

### ISSUE THREAD

**Issue by ClintLiddick** [PyryM/truss#29]
I'm looking for a fix (possibly using SDL's own configure script will resolve this? I've built it standalone before. I should try again.), but this is the error.

```
[ 99%] Building C object CMakeFiles/SDL2.dir/src/timer/unix/SDL_systimer.c.o
[100%] Linking C shared library libSDL2-2.0.so
CMakeFiles/SDL2.dir/src/video/wayland/SDL_waylandevents.c.o: In function `wl_registry_bind':
/usr/include/wayland-client-protocol.h:1061: undefined reference to `wl_proxy_marshal_constructor_versioned'
CMakeFiles/SDL2.dir/src/video/wayland/SDL_waylandtouch.c.o: In function `wl_registry_bind':
/usr/include/wayland-client-protocol.h:1061: undefined reference to `wl_proxy_marshal_constructor_versioned'
CMakeFiles/SDL2.dir/src/video/wayland/SDL_waylandvideo.c.o: In function `wl_registry_bind':
/usr/include/wayland-client-protocol.h:1061: undefined reference to `wl_proxy_marshal_constructor_versioned'
/usr/include/wayland-client-protocol.h:1061: undefined reference to `wl_proxy_marshal_constructor_versioned'
/usr/include/wayland-client-protocol.h:1061: undefined reference to `wl_proxy_marshal_constructor_versioned'
CMakeFiles/SDL2.dir/src/video/wayland/SDL_waylandvideo.c.o:/usr/include/wayland-client-protocol.h:1061: more undefined references to `wl_proxy_marshal_constructor_versioned' follow
collect2: error: ld returned 1 exit status
CMakeFiles/SDL2.dir/build.make:3709: recipe for target 'libSDL2-2.0.so.0.4.0' failed
make[5]: *** [libSDL2-2.0.so.0.4.0] Error 1
CMakeFiles/Makefile2:136: recipe for target 'CMakeFiles/SDL2.dir/all' failed
make[4]: *** [CMakeFiles/SDL2.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/sdl_EXTERNAL.dir/build.make:111: recipe for target 'sdl_EXTERNAL-prefix/src/sdl_EXTERNAL-stamp/sdl_EXTERNAL-build' failed
make[2]: *** [sdl_EXTERNAL-prefix/src/sdl_EXTERNAL-stamp/sdl_EXTERNAL-build] Error 2
CMakeFiles/Makefile2:141: recipe for target 'CMakeFiles/sdl_EXTERNAL.dir/all' failed
make[1]: *** [CMakeFiles/sdl_EXTERNAL.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by ClintLiddick** [comment]
Ok interesting. The version downloaded fails to compile on its own for default configurations with cmake and autotools.

**Comment by ClintLiddick** [comment]
truss compiles and runs when using the system SDL2, so maybe you should attempt `find_package` first and then fallback to the external project?

**Comment by psigen** [comment]
We can probably just upgrade to a version that works for you as well.  Can you post the system packaged version?

**Comment by ClintLiddick** [comment]
The latest SDL 2.0.4 I downloaded didn't build either. So there's probably a deb patch or specific build options to work on Wayland.

```
ii  libsdl2-2.0-0:amd64      2.0.4+dfsg2-1         amd64        Simple DirectMedia Layer
ii  libsdl2-dev              2.0.4+dfsg2-1         amd64        Simple DirectMedia Layer development files
```
